### ISSUE TITLE
Multi-Dimensional HGP codes. / 3D Toric Code

### ISSUE THREAD

**Issue by oliverweissl** [Infleqtion/qLDPC#33]
Really nice library, and it seems very useful for one of my projects!
I was wondering if you plan to extend the HGP functionality to produce n-dimensional codes aswell?
This would be very helpful to construct a 3D Toric code for example.

**Comment by perlinm** [comment]
Thank you! I would be happy to add additional functionality, particularly if it is helpful or useful to somebody :slightly_smiling_face:

I am not sure what an n-dimensional HGP code is, though, or how exactly that would work.  Do you have a reference I could use to understand it?  Is [this](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.122.230501) the right place to look?

**Comment by perlinm** [comment]
Assuming that I understand the request, I think Eq. 14 [here](https://arxiv.org/pdf/1810.01519v2.pdf) gives me a concrete construction that I can implement for the product of `n` classical codes.  However, this product gives me an `n`-complex, in which any pair of adjacent boundary operators can be used to define a CSS code.  So in total, the `n`-complex gives me `n-1` CSS codes.  Which of these codes is "the" hypergraph product of `n` classical codes?

Apologies in advance if the things I am saying do not make sense.  I am learning this stuff on the fly so I may be getting concepts or terminology wrong :sweat_smile:

**Comment by oliverweissl** [comment]
Hey, thanks for looking at the issue! Im not aware of any generalizable construction method implemented yet. However the 3D toric is coded in panqec. Im struggeling myself to understand it as Im developing a decoder for my masters thesis. However the current libraries are pretty restricted in the type of codes they have.

I have read a paper that describes the construction a bit differently to the one you have, I will try to find kt again!

**Comment by perlinm** [comment]
I see.  Are you simply after the n-dimensional toric code?  If so, perhaps I can add just that.  I would still be interested in adding a general hypergraph product code, though.

**Comment by oliverweissl** [comment]
Yes im trying to validate my decoder concept on different type of codes. For now Im sticking to Toric codes, because the lack of generalizable construction. Also only Torica would be a nice to cross validate different libraries :)

**Comment by perlinm** [comment]
I'll let @oliverweissl close this issue if+when it's addressed satisfactorily :slightly_smiling_face:

**Comment by oliverweissl** [comment]
Hey i saw that the construction of the HGP  for 2 classical codes (based on [arXiv:2202.01702]) is quite elegant in code.
I have similar formulation for HGP of 3 classical codes [arXiv:2409.04300], maybe this is useful

if not please close this :D

**Comment by perlinm** [comment]
Sorry for the delayed response!

Generally speaking, more code constructions sounds nice to have.  Based on the text between Eqs. (3) and (4) of [your paper](https://arxiv.org/pdf/2409.04300v1), it sounds like your 3D HGP code construction is equivalent to the strategy I used to construct the [GeneralizedSurfaceCode](https://github.com/Infleqtion/qLDPC/blob/642f623aa12f1b9933932f3f380675126f29c334/qldpc/codes/quantum.py#L1142-L1149) (note that each `Chain_complex.tensor_product` here [is equivalent to a hypergraph product](https://github.com/Infleqtion/qLDPC/blob/642f623aa12f1b9933932f3f380675126f29c334/qldpc/codes/quantum_test.py#L123-L131)).  Does that sound correct?  If so, maybe we rather than hard-coding the 3-fold HGP, it would be better to go ahead and inductively define the n-fold HGP.

**Comment by oliverweissl** [comment]
Hey thanks for the reply! This sounds correct to me. And having n-fold construction would be quite elegant, also I think you would be the first library that does this ( at least that im aware of)
